2018-12-10 13:57:09+0800 [-] Log opened.
2018-12-10 13:57:10+0800 [-] EchoFactory starting on 8002
2018-12-10 13:57:10+0800 [-] Starting factory <__main__.EchoFactory object at 0x043ED270>
2018-12-10 13:57:10+0800 [-] Listening....
2018-12-10 13:57:10+0800 [-] 
2018-12-10 13:57:53+0800 [Echo,0,192.168.0.105] info:0102030405060708090A0B0C disconnected
	
2018-12-10 13:58:03+0800 [Echo,1,192.168.0.105] info:0102030405060708090A0B0C disconnected
	
2018-12-10 13:58:41+0800 [Echo,2,192.168.0.105] info:0102030405060708090A0B0C disconnected
	
2018-12-10 14:00:32+0800 [-] info:0102030405060708090A0B0C timeout
2018-12-10 14:00:32+0800 [-] info:0102030405060708090A0B0C disconnected
	
2018-12-10 14:01:49+0800 [-] Log opened.
2018-12-10 14:01:49+0800 [-] EchoFactory starting on 8002
2018-12-10 14:01:49+0800 [-] Starting factory <__main__.EchoFactory object at 0x03E4D2B0>
2018-12-10 14:01:49+0800 [-] Listening....
2018-12-10 14:01:49+0800 [-] 
2018-12-10 14:02:09+0800 [-] 'error:(2003, "Can\'t connect to MySQL server on \'47.106.125.221\' (timed out)")'
2018-12-10 14:02:09+0800 [-] 'error:(2003, "Can\'t connect to MySQL server on \'47.106.125.221\' (timed out)")'
2018-12-10 14:02:09+0800 [-] Unhandled error in Deferred:
2018-12-10 14:02:09+0800 [-] Unhandled Error
	Traceback (most recent call last):
	  File "C:\Python\Python36-32\lib\site-packages\twisted\internet\base.py", line 1252, in mainLoop
	    self.runUntilCurrent()
	  File "C:\Python\Python36-32\lib\site-packages\twisted\internet\base.py", line 851, in runUntilCurrent
	    f(*a, **kw)
	  File "C:\Python\Python36-32\lib\site-packages\twisted\internet\defer.py", line 500, in errback
	    self._startRunCallbacks(fail)
	  File "C:\Python\Python36-32\lib\site-packages\twisted\internet\defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "C:\Python\Python36-32\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "E:\Python-L\Plat\Iotserver\server.py", line 142, in execute_get_type
	    _stream_type=sqlconnect.runInteraction(self.get_stream_type,model_id[0])
	builtins.TypeError: 'NoneType' object is not subscriptable
	
2018-12-10 14:02:59+0800 [-] info:0102030405060708090A0B0C timeout
2018-12-10 14:02:59+0800 [-] info:0102030405060708090A0B0C disconnected
	
2018-12-10 14:06:06+0800 [-] Log opened.
2018-12-10 14:06:07+0800 [-] EchoFactory starting on 8002
2018-12-10 14:06:07+0800 [-] Starting factory <__main__.EchoFactory object at 0x03C1D2B0>
2018-12-10 14:06:07+0800 [-] Listening....
2018-12-10 14:06:07+0800 [-] 
2018-12-10 14:07:50+0800 [Echo,0,192.168.0.105] info:0102030405060708090A0B0C disconnected
	
2018-12-10 14:09:04+0800 [Echo,1,192.168.0.105] info:0102030405060708090A0B0C disconnected
	
2018-12-10 14:10:34+0800 [-] Log opened.
2018-12-10 14:10:34+0800 [-] EchoFactory starting on 8002
2018-12-10 14:10:34+0800 [-] Starting factory <__main__.EchoFactory object at 0x03B1D2B0>
2018-12-10 14:10:34+0800 [-] Listening....
2018-12-10 14:10:34+0800 [-] 
2018-12-10 14:17:05+0800 [Echo,0,192.168.0.105] error:CRC ERROR
2018-12-10 14:17:05+0800 [-] info:0102030405060708090A0B0C disconnected
	
2018-12-10 14:18:04+0800 [-] info:0102030405060708090A0B0C timeout
